-- ============================================================================
-- FORECLOSUREFINDER AI — PHASE 2 EVOLUTION SCHEMA MIGRATION
-- Target Database: PostgreSQL 16+
-- Adds advanced AI multi-agent tables, motivation scores, wholesaling grades,
-- heatmaps, and public notice OCR pipeline metadata.
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ════════════════════════════════════════════════════════════════════════════
-- 1. AI AGENT PORTALS & CONNECTOR DISCOVERY REGISTRIES
-- ════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS county_discovery_registry (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  county VARCHAR(100) NOT NULL,
  state VARCHAR(2) NOT NULL,
  portal_name VARCHAR(150) NOT NULL,
  url VARCHAR(512) NOT NULL,
  platform_type VARCHAR(100) NOT NULL,              -- e.g. 'Recorder', 'Tax Delinquency', 'Sheriff'
  captcha_required BOOLEAN DEFAULT FALSE,
  ocr_required BOOLEAN DEFAULT FALSE,
  search_method VARCHAR(100),                       -- e.g. 'Name Index', 'Parcel Search', 'GIS Mapping'
  api_available BOOLEAN DEFAULT FALSE,
  authentication_required BOOLEAN DEFAULT FALSE,
  data_quality_score INT DEFAULT 0 CONSTRAINT chk_discovery_quality CHECK (data_quality_score BETWEEN 0 AND 100),
  connector_status VARCHAR(50) DEFAULT 'pending',   -- e.g. 'pending', 'approved', 'declined'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS connector_templates (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  registry_id UUID REFERENCES county_discovery_registry(id) ON DELETE CASCADE,
  connector_code TEXT NOT NULL,                     -- Autogenerated Playwright/Crawlee Node.js script
  validation_checklist JSONB NOT NULL,              -- Checklist of query params and extraction success flags
  estimated_maintenance_score INT DEFAULT 100,      -- Stability rating (0-100)
  status VARCHAR(50) DEFAULT 'draft',               -- e.g. 'draft', 'approved', 'deployed'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ════════════════════════════════════════════════════════════════════════════
-- 2. INVESTOR MOTIVATION, ARV, WHOLESALE ANALYSIS & OUTREACH PREPARATION
-- ════════════════════════════════════════════════════════════════════════════

-- Append new fields to property_enrichments if they don't exist
ALTER TABLE property_enrichments 
  ADD COLUMN IF NOT EXISTS motivation_score INT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS motivation_tier VARCHAR(20) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS motivation_reason_codes TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS arv DECIMAL(15, 2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS estimated_repairs DECIMAL(15, 2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS suggested_cash_offer DECIMAL(15, 2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS mao DECIMAL(15, 2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS wholesale_fee_potential DECIMAL(15, 2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS deal_grade VARCHAR(2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS deal_explanation TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS outreach_readiness_sms BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS outreach_readiness_mail BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS outreach_readiness_call BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS outreach_readiness_email BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS outreach_readiness_door BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS outreach_recommendation TEXT DEFAULT NULL;

-- ════════════════════════════════════════════════════════════════════════════
-- 3. AI SELLER DEMOGRAPHIC PERSONAS
-- ════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS seller_personas (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  lead_id UUID NOT NULL REFERENCES foreclosure_leads(id) ON DELETE CASCADE,
  persona_type VARCHAR(100) NOT NULL,               -- e.g. 'Long-Term Owner', 'Probate Heir', 'Out-Of-State Landlord'
  confidence_score INT NOT NULL CONSTRAINT chk_persona_confidence CHECK (confidence_score BETWEEN 0 AND 100),
  contact_strategy TEXT NOT NULL,
  offer_type VARCHAR(100) NOT NULL,                 -- e.g. 'CASH_OFFER', 'SUBJECT_TO', 'SELLER_FINANCE'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(lead_id, persona_type)                     -- One profile type per property
);

-- ════════════════════════════════════════════════════════════════════════════
-- 4. GEOGRAPHIC MARKET TRENDS & ANALYTICS HEATMAPS
-- ════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS heatmap_metrics (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  zip_code VARCHAR(10) NOT NULL,
  city VARCHAR(100) NOT NULL,
  county_code VARCHAR(20) NOT NULL REFERENCES counties(county_code) ON DELETE CASCADE,
  state VARCHAR(2) NOT NULL,
  foreclosure_count INT DEFAULT 0,
  probate_count INT DEFAULT 0,
  tax_delinquency_count INT DEFAULT 0,
  vacancy_count INT DEFAULT 0,
  investor_purchase_count INT DEFAULT 0,
  cash_transaction_count INT DEFAULT 0,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(zip_code)
);

CREATE TABLE IF NOT EXISTS market_trends (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  region_type VARCHAR(50) NOT NULL,                 -- 'ZIP', 'COUNTY', 'CITY', 'MSA'
  region_value VARCHAR(100) NOT NULL,
  month_start DATE NOT NULL,
  average_arv DECIMAL(15,2) DEFAULT NULL,
  average_equity_pct DECIMAL(5,2) DEFAULT NULL,
  listing_volume_change_pct DECIMAL(5,2) DEFAULT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(region_type, region_value, month_start)
);

-- ════════════════════════════════════════════════════════════════════════════
-- 5. PUBLIC NOTICE OCR PIPELINE METADATA
-- ════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS ocr_documents (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  lead_id UUID REFERENCES foreclosure_leads(id) ON DELETE SET NULL,
  file_url VARCHAR(512) NOT NULL,
  document_type VARCHAR(100) NOT NULL,              -- e.g. 'Newspaper Scan', 'Court PDF', 'Deed Image'
  raw_text TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ocr_extractions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  document_id UUID NOT NULL REFERENCES ocr_documents(id) ON DELETE CASCADE,
  extracted_field VARCHAR(100) NOT NULL,            -- e.g. 'plaintiff', 'caseNumber', 'trustee'
  extracted_value TEXT NOT NULL,
  confidence_score DECIMAL(5,2) NOT NULL,           -- e.g. 98.45 (%)
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ════════════════════════════════════════════════════════════════════════════
-- 6. SKIP TRACE CONTACT ABSTRACTION LAYER
-- ════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS phones (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  lead_id UUID NOT NULL REFERENCES foreclosure_leads(id) ON DELETE CASCADE,
  phone_number VARCHAR(20) NOT NULL,
  phone_type VARCHAR(50),                           -- e.g. 'Mobile', 'Landline', 'VoIP'
  is_verified BOOLEAN DEFAULT FALSE,
  confidence_score INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS emails (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  lead_id UUID NOT NULL REFERENCES foreclosure_leads(id) ON DELETE CASCADE,
  email_address VARCHAR(255) NOT NULL,
  is_verified BOOLEAN DEFAULT FALSE,
  confidence_score INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS relatives (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  lead_id UUID NOT NULL REFERENCES foreclosure_leads(id) ON DELETE CASCADE,
  full_name VARCHAR(255) NOT NULL,
  relationship VARCHAR(100),                        -- e.g. 'Spouse', 'Child', 'Sibling'
  phone VARCHAR(20),
  email VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ════════════════════════════════════════════════════════════════════════════
-- 7. METRO EXPANSION & RADIUS SEARCH REGIONS
-- ════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS expansion_regions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  center_city VARCHAR(100) NOT NULL,
  center_state VARCHAR(2) NOT NULL,
  radius_miles INT NOT NULL,
  discovered_counties JSONB NOT NULL,
  discovered_zipcodes JSONB NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ════════════════════════════════════════════════════════════════════════════
-- INDEXES & PERFORMANCE OPTIMIZATION
-- ════════════════════════════════════════════════════════════════════════════

CREATE INDEX IF NOT EXISTS idx_county_discovery_state ON county_discovery_registry (state, county);
CREATE INDEX IF NOT EXISTS idx_seller_personas_lead ON seller_personas (lead_id);
CREATE INDEX IF NOT EXISTS idx_heatmap_zip ON heatmap_metrics (zip_code);
CREATE INDEX IF NOT EXISTS idx_phones_lead ON phones (lead_id);
CREATE INDEX IF NOT EXISTS idx_emails_lead ON emails (lead_id);
CREATE INDEX IF NOT EXISTS idx_relatives_lead ON relatives (lead_id);
